### ISSUE TITLE
plainte (erreur et one-liner) 

### ISSUE THREAD

**Issue by Sparayack** [club-de-math/Numcraft#1]
Bonjour, première fois que je lance le code, et là, C'EST LE DRAME première erreur dans votre code. Je suis aussi très déçu que votre projet ne soit pas codé en one-liner, venant de développeurs comme vous, je m'attendais à mieux!!!
Sinon le jeu a l'air sympa. :)

Signé, a friend.

**Comment by The-ZmaZe** [comment]
Issue In dev

**Comment by Sparayack** [comment]
baleks frr

**Comment by The-ZmaZe** [comment]
Issue resolved
